# This file was generated by SquareLine Studio
# SquareLine Studio version: SquareLine Studio 1.2.3
# LVGL version: 8.2.0
# Project name: SquareLine_Project


def btnclick(event_struct):
    return


def update_val(event_struct):
    print(str(event_struct))
    return


